### ISSUE TITLE
Qps和Busrt设置

### ISSUE THREAD

**Issue by Yuanyiyi** [openkruise/kruise-game#101]
**What happened**:
当前服务与ApiServer的QPS和Burst使用默认配置（QPS=20, Burst=30）; 在一些业务场景下，默认QPS和Burst可能不足以支撑，需要调整QPS和Burst。
**What you expected to happen**:
希望服务支持用户自定义QPS和Burst。例如在部署服务的command下设置
args:
        - --api-server-qps=5
        - --api-server-qps-burst=10

**Comment by ringtail** [comment]
cc @chrisliu1995

**Comment by chrisliu1995** [comment]
> 服务默认的qps为20，burst为30；希望外部可设置。

可以通过增加controller的启动参数来自定义设置。你有兴趣设计开发这个feature吗？

**Comment by chrisliu1995** [comment]
我们看到了您的PR，感谢贡献。建议先在此提交您的设计。方便社区伙伴们共同review一下 @Yuanyiyi

**Comment by ringtail** [comment]
close due to https://github.com/openkruise/kruise-game/pull/108
