### ISSUE TITLE
New image update strategy

### ISSUE THREAD

**Issue by sFireFrog** [openkruise/kruise-game#111]
It is recommended to add an update strategy that allows the image to be updated only under certain pod states.
When the status of the container is controlled through scripts, there will be the following problems：
 1.If the pod status is allocated, the image will also be updated.This will affect players who are playing.
 2.If you want to solve problem 1, you need to rebuild gss.yaml. If there is a scaling mechanism, you also need to rebuild scaled.yaml, and then delete the previous yaml, which is very troublesome.Of course there are other ways.

**Comment by chrisliu1995** [comment]
refer to: https://openkruise.io/kruisegame/best-practices/session-based-game/#game-room-hot-update
