### ISSUE TITLE
Kruise Game Dashboard Update

### ISSUE THREAD

**Issue by ringtail** [openkruise/kruise-game#139]

**Comment by ringtail** [comment]
* 增加Label分组筛选功能
* 增加定向资源管理功能

**Comment by chrisliu1995** [comment]
Currently, the OKG Dashboard has implemented basic game server management functions based on [KubeSphere](https://github.com/kubesphere), such as:

- GameServer status statistics
- GameServer status display
- GameServerSet status display
- Targeted updates for individual objects

Building on these features, game operation engineers can carry out simple maintenance tasks through the OKG Dashboard. However, for more complex operational scenarios, the current support of the Dashboard is not yet sufficient. We hope to enhance the Dashboard's capabilities to include the following features:

- Support for pagination when displaying batches of GameServer/GameServerSet
- Filter GameServers through specific fields (Name/Label/Image, etc.)
- Select multiple GameServers and update fields in batch

**Comment by timilehin2000** [comment]
Hello, Please can i get more explanation on what this project is all about

**Comment by angad-singhh** [comment]
Hey @chrisliu1995,
I am interested in working on this project, please share how to proceed with this or any community slack channel specifically for OKG/LFX mentorship.

**Comment by ringtail** [comment]
@angad-singhh @timilehin2000 Join our discord（https://discord.gg/w8Nsuxtp）

**Comment by kirtanchandak** [comment]
Hey @ringtail can you share the discord link again, this is link is expired!

**Comment by kirtanchandak** [comment]
I am Kirtan a Full Stack Developer from India. Would love to work on the project this LFX term!

**Comment by uday-biswas** [comment]
Hello @ringtail , the discord invite link seems expired, can you share it one more time ?

**Comment by ringtail** [comment]
> Hello @ringtail , the discord invite link seems expired, can you share it one more time ?

https://discord.gg/vRz86Fxk

**Comment by literalEval** [comment]
Hey @ringtail 

The discord link shows to be invalid. Moreover, what is the pretest for this project ?

Thanks.

**Comment by ringtail** [comment]
> Hey @ringtail
> 
> The discord link shows to be invalid. Moreover, what is the pretest for this project ?
> 
> Thanks.

https://discord.gg/T48ff4m7

**Comment by chrisliu1995** [comment]
Newest dashboard already published.

**Comment by chrisliu1995** [comment]
Newest dashboard already published.

https://openkruise.io/kruisegame/user-manuals/game-dashboard#multi-clusters-mode
