### ISSUE TITLE
Whether serviceQuality can provide customized restart policies, such as Always, Onfailure, Never, to solve the problem of data inconsistency caused by some program crashes;

### ISSUE THREAD

**Issue by fanhao99** [openkruise/kruise-game#14]
Whether serviceQualities can provide customized restart policies, such as Always, Onfailure, Never. You can choose to restart the whole pod when some programs crash to solve the problem of data inconsistency caused by some program crashes;
-------------------------------------------------------------------------------------------------------------------------------------------------
serviceQualities 是否可以提供自定义restartpolicry，如Always、Onfailure、Never，可以选择部分程序崩溃整个pod进行重启，解决部分程序崩溃造成数据不一致的问题；

**Comment by ringtail** [comment]
> ## Whether serviceQualities can provide customized restart policies, such as Always, Onfailure, Never. You can choose to restart the whole pod when some programs crash to solve the problem of data inconsistency caused by some program crashes;
> serviceQualities 是否可以提供自定义restartpolicry，如Always、Onfailure、Never，可以选择部分程序崩溃整个pod进行重启，解决部分程序崩溃造成数据不一致的问题；

我理解您希望通过服务质量解决的问题是故障场景下的自动化运维策略，是否是这种的场景。
