### ISSUE TITLE
希望web管理页面增加运维状态

### ISSUE THREAD

**Issue by cy5649293** [openkruise/kruise-game#153]
![image](https://github.com/openkruise/kruise-game/assets/33860092/e40bdaa4-a058-40c5-8eb3-a0caa084b242)
![image](https://github.com/openkruise/kruise-game/assets/33860092/017d32be-e1be-4c75-b079-98fbfad76c53)
如图所示，希望新增一个下拉框，可以直接选择的，这样可以直接配置gs的具体状态

**Comment by chrisliu1995** [comment]
感谢反馈。可以关注下OKG Dashboard v2.0

设计文档如下：https://github.com/CloudNativeGame/kruise-game-dashboard/issues/5

**Comment by jayesh9747** [comment]
@ringtail  @chrisliu1995  can i work on this ?

**Comment by chrisliu1995** [comment]
> @ringtail @chrisliu1995 can i work on this ?

Sure. Is that clear for you to begin your work? Cause the issue is described by Chinese.

**Comment by jayesh9747** [comment]
@chrisliu1995  Sure, I used Google Translate for this.

**Comment by chrisliu1995** [comment]
> @chrisliu1995 Yes, I was able to get the context of the issue using Google Translate, but could you explain it a bit more?

Great. You know, There are some opsState value that OKG provides by default, including 'WaitToBeDeleted', 'None', 'Allocated', 'Maintaining', 'Kill'. Those values should be shown in drop down box.

Besides, users can also set GameServers' opsState by any values, so that you have to allow users to fill in any value they want.

**Comment by jayesh9747** [comment]
> > @chrisliu1995 Yes, I was able to get the context of the issue using Google Translate, but could you explain it a bit more?
> 
> Great. You know, There are some opsState value that OKG provides by default, including 'WaitToBeDeleted', 'None', 'Allocated', 'Maintaining', 'Kill'. Those values should be shown in drop down box, and users can select the value they want.
> 
> Besides, users can also set GameServers' opsState by any values, so that you have to allow users to fill in any value they want.

that means we need the below type functionality dropdown + userInput 
![image](https://github.com/openkruise/kruise-game/assets/123955234/34b111c3-75c9-441e-94ed-4f11992eec2e)

**Comment by chrisliu1995** [comment]
The function is completed. Thanks @jayesh9747
