### ISSUE TITLE
Simultaneous Display of Data and 'No Data Found' Message

### ISSUE THREAD

**Issue by jayesh9747** [openkruise/kruise-game#155]
![image](https://github.com/openkruise/kruise-game/assets/123955234/c59de189-6977-4953-b73e-f2a11ba16b8c)

**Comment by jayesh9747** [comment]
@chrisliu1995  @ringtail  can I start work to fix this issue?

**Comment by chrisliu1995** [comment]
> @chrisliu1995 @ringtail can I start work to fix this issue?

Sure. Have you figured out why the problem occurred?

**Comment by jayesh9747** [comment]
> > @chrisliu1995 @ringtail can I start work to fix this issue?
> 
> Sure. Have you figured out why the problem occurred?

Not now , but i will find very soon and fix this . thank you

**Comment by jayesh9747** [comment]
@chrisliu1995, this issue is not related to the extension. It was not fixed by pushing code into the extension repository. The solution involved changing code in the main repository of KubeSphere. The cause of this issue was that both state variables were true, causing both components to render at the same time. Could you suggest how to approach this correctly?

**Comment by chrisliu1995** [comment]
> @chrisliu1995, this issue is not related to the extension. It was not fixed by pushing code into the extension repository. The solution involved changing code in the main repository of KubeSphere. The cause of this issue was that both state variables were true, causing both components to render at the same time. Could you suggest how to approach this correctly?

You can open an issue in KubeSphere community( https://github.com/kubesphere/kubesphere )
