### ISSUE TITLE
can we have a slack channel for kruise-game ?

### ISSUE THREAD

**Issue by ashish111333** [openkruise/kruise-game#168]
request for a kruise-game channel on slack.

**Comment by ringtail** [comment]
https://discord.gg/qXMY5qvN

**Comment by ringtail** [comment]
@ashish111333 We have discord channel

**Comment by shivkr6** [comment]
The Discord link expired. Can you provide me another link? :) @ringtail

**Comment by ringtail** [comment]
> The Discord link expired. Can you provide me another link? :) @ringtail

https://discord.gg/NCpXQwJZWr

**Comment by furykerry** [comment]
@ringtail @chrisliu1995 kruise-game can also use the kruise slack channel
https://kubernetes.slack.com/channels/openkruise
