### ISSUE TITLE
AlibabaCloud-NLB网络插件处理慢

### ISSUE THREAD

**Issue by cnxh** [openkruise/kruise-game#186]
在使用AlibabaCloud-NLB网络插件时，一次性部署100个GameServer, 大概需要5分钟，才能将所有GameServer的网络状态变成ready， 希望可以优化下，谢谢。

**Comment by chrisliu1995** [comment]
ccm调用lb listener 相关API速度较慢，svc ready在批量处理时会堆积导致整体速度慢

**Comment by ringtail** [comment]
可以尝试将SVC改成External Trafic为Local，可以加速节点绑定。

**Comment by chrisliu1995** [comment]
> 可以尝试将SVC改成External Trafic为Local，可以加速节点绑定。

当前nlb模型使用的即是local模式
