### ISSUE TITLE
可以通过环境变量方式获取slb ip和端口号呢？

### ISSUE THREAD

**Issue by gopower** [openkruise/kruise-game#33]
![92583f399acbe773bbec5d2bbaa6e7d4](https://user-images.githubusercontent.com/96470241/209894816-e0ce5615-8f06-40ab-9a12-afb34cbad40a.png)

**Comment by chrisliu1995** [comment]
网络信息生成后会回填到pod的annotations中，您通过设置ENV downwardAPI fieldpath，解析结果后可以实现获取对应的ip端口号。

但值得注意的是，很多网络插件是异步生成接入层网络，所以在pod创建时网络信息很可能未生成出来，此时需要手动原地更新下对应容器才可以实现环境变量的重载。原地升级pod容器的方式可参考：https://openkruise.io/zh/docs/user-manuals/containerrecreaterequest
