### ISSUE TITLE
Hostport not allocated for rebuilt Pods with potential for intermittent error

### ISSUE THREAD

**Issue by alvin-7** [openkruise/kruise-game#77]
## Backgroud
Firstly, please note the following series of events:

A Pod has been established within the cluster utilizing OKG for GSS, complete with requested hostport and performs regularly.
Upon updating the image and GSS configuration incorporating a ReadinessProbe, an error arises preventing the new Pod from launching (the grpc ReadinessProbe was applied, but presently, the cluster isn't capable of accommodating this new feature).
In response, I removed the problematic ReadinessProbe configuration which prompted a rebuild, leading to the successful creation of the new Pod.
Curiously, after its establishment, the new Pod neglected to request a hostport.

Upon inspecting the controller logs, it appears that the original Pod had not triggered a deallocation upon deletion. As such, the controller perpetually views the hostport of the Pod as requested. This situation merits further investigation of the related allocation processes to prevent potential errors in similar future scenarios.

## Query
How can such instances be avoided? Is there any mechanism to verify the deallocation of the hostport when the Pod is deleted? Any advice regarding resolving this issue would be greatly appreciated.

**Comment by chrisliu1995** [comment]
For the Kubernetes-Hostport type, we will add a new cache to record the pod corresponding hostPorts allocation. When an exception occurs, pod creation fails, and pod add events are continuously generated, the plugin will patch the pod with allocated hostPorts base on the cache until the pod is actually created, or pod is completely deleted, when the hostPorts are also recycled.
