### ISSUE TITLE
Network annotation may not be properly configured during Pod deletion and rebuild

### ISSUE THREAD

**Issue by alvin-7** [openkruise/kruise-game#78]
This issue outlines that the annotation tied to the network may not be updated correctly during the deletion and rebuilding phases of a Pod.

## Here's the sequence of events:

1. Three Pods were established within the cluster using OKG's GSS and are currently performing as per normal. The network annotations for all these Pods have been correctly configured.
2. Subsequently, I modified the GSS-associated image, which triggered an automatic rebuild of the three Pods (this 'ReCreate' action was aligned with the Pod update strategy).
3. After the rebuild was completed, there were occasional instances when the network annotation for one or more Pods was not set correctly.

## The current resource situation can be summarized as follows:

1. A hostport allocation is observable from the Pod's yaml file.
2. However, pertaining to the ‘GameServer’ resource (an OKG resource that should correspond on a one-to-one basis with the Pod), no rebuild was initiated after the new Pod was rebuilt. The 'age' parameter retains its pre-rebuild value, casting doubts on the correctness of this process.

**Comment by chrisliu1995** [comment]
When the pod is deleted and recreated, the gs with the same name is not deleted. At this time, the gs network status is ready, which is in line with the expected status, and it will not trigger the network update, which is an occasional scenario. We will consider this issue and fix it.
